language: minimal
services:
  - docker

jobs:
  include:
    - stage: test
      if: type = pull_request
      script: bash build-image base
    - stage: test
      if: type = pull_request
      script: bash build-image golang
    - stage: deploy
      if: type = push AND branch = master
      script: bash build-image all push
