#!/bin/bash -e

if [[ "$1" == "base" || "$1" == "all" ]]; then
  docker build --no-cache -t michaelgrifalconi/git2go:alpine-base-v"$(cat version)" -f ./images/alpine-base/Dockerfile .
  if [[ "$2" == "push" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push michaelgrifalconi/git2go:alpine-base-v"$(cat version)"
  fi
fi

if [[ "$1" == "golang" || "$1" == "all" ]]; then
  docker build --no-cache -t michaelgrifalconi/git2go:alpine-golang-v"$(cat version)" -f ./images/alpine-golang/Dockerfile .
  if [[ "$2" == "push" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker push michaelgrifalconi/git2go:alpine-golang-v"$(cat version)"
  fi
fi




