#!/bin/bash -e

# TODO: need to handle tag versions

if [[ "$1" == "base" || "$1" == "all" ]]; then
  docker build --no-cache -t michaelgrifalconi/git2go:alpine-base-0 -f ./images/alpine-base/Dockerfile .
  if [[ "$2" == "push" ]]; then
    echo "Here I would push the image to my docker account. IF I HAD ONE."
  fi
fi

if [[ "$1" == "golang" || "$1" == "all" ]]; then
  docker build --no-cache -t michaelgrifalconi/git2go:alpine-golang-0 -f ./images/alpine-golang/Dockerfile .
  if [[ "$2" == "push" ]]; then
   echo "Here I would push the image to my docker account. IF I HAD ONE."
  fi
fi




